# Generated by Django 4.2.26 on 2026-01-05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assets", "0002_alter_assetrecord_created_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProxyMapping",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("proxy", models.CharField(max_length=128, unique=True)),
                ("display_name", models.CharField(max_length=256)),
                ("remark", models.CharField(blank=True, default="", max_length=256)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "assets_proxy_mapping",
                "ordering": ("-created_at",),
                "verbose_name": "Proxy Mapping",
                "verbose_name_plural": "Proxy Mappings",
            },
        ),
    ]
