# Generated by Django 4.2.13 on 2026-03-19 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_alter_assetsyncchange_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrecord',
            name='asset_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='assetrecord',
            name='canonical_key',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
