# Generated by Django 4.2.13 on 2026-03-19 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0007_add_asset_type_canonical_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('cmdb', 'CMDB'), ('monitoring', '监控平台'), ('itsm', '工单/ITSM'), ('other', '其他')], default='other', max_length=32)),
                ('is_enabled', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Source',
                'verbose_name_plural': 'Asset Sources',
                'db_table': 'assets_asset_source',
                'ordering': ('key',),
            },
        ),
        migrations.AddField(
            model_name='assetsyncrun',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_runs', to='assets.assetsource'),
        ),
    ]
