# Generated by Django 4.2.13 on 2026-03-20 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0008_assetsource_assetsyncrun_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=128)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('fields', models.JSONField(default=list)),
                ('unique_key', models.JSONField(default=list)),
                ('script_id', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Model',
                'verbose_name_plural': 'Asset Models',
                'db_table': 'assets_asset_model',
            },
        ),
    ]
