[pytest]
DJANGO_SETTINGS_MODULE = core.settings.base
django_find_project = false
pythonpath = src
python_files = tests.py test_*.py *_tests.py
addopts = -ra --disable-warnings --cov=src --cov-report=term-missing --nomigrations
log_cli = true
log_cli_level = INFO
