# Generated by Django 4.2.26 on 2025-11-12 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgearticle',
            options={'ordering': ('-last_edited_at',), 'verbose_name': 'Knowledge Article', 'verbose_name_plural': 'Knowledge Articles'},
        ),
        migrations.AlterField(
            model_name='knowledgearticle',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='knowledgearticle',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
