# Generated by Django 4.2.26 on 2025-11-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_seed_ip_regex_plugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptplugin',
            name='builtin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scriptplugin',
            name='component',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='scriptplugin',
            name='group',
            field=models.CharField(default='tools', max_length=60),
        ),
        migrations.AddField(
            model_name='scriptplugin',
            name='route',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='scriptplugin',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
