# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from probes.v1 import gateway_pb2 as probes_dot_v1_dot_gateway__pb2


class ProbeGatewayStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.stream_stream(
                '/onepro.probes.v1.ProbeGateway/Connect',
                request_serializer=probes_dot_v1_dot_gateway__pb2.ProbeMessage.SerializeToString,
                response_deserializer=probes_dot_v1_dot_gateway__pb2.ServerMessage.FromString,
                )


class ProbeGatewayServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Connect(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProbeGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.stream_stream_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=probes_dot_v1_dot_gateway__pb2.ProbeMessage.FromString,
                    response_serializer=probes_dot_v1_dot_gateway__pb2.ServerMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'onepro.probes.v1.ProbeGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProbeGateway(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Connect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/onepro.probes.v1.ProbeGateway/Connect',
            probes_dot_v1_dot_gateway__pb2.ProbeMessage.SerializeToString,
            probes_dot_v1_dot_gateway__pb2.ServerMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
