# Generated by Django 4.2.13 on 2026-03-18 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('scope', models.CharField(choices=[('global', 'Global'), ('monitoring_task', 'Monitoring Task'), ('asset', 'Asset'), ('probe', 'Probe')], default='global', max_length=32)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('enabled', models.BooleanField(default=True)),
                ('severity', models.CharField(default='warning', max_length=32)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('channels', models.JSONField(blank=True, default=list, help_text='Preferred channels for this rule')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert Rule',
                'verbose_name_plural': 'Alert Rules',
                'db_table': 'alerts_rule',
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(help_text='Origin of the alert, e.g. monitoring, probes', max_length=64)),
                ('event_type', models.CharField(help_text='Logical alert type, e.g. detection_failure', max_length=64)),
                ('severity', models.CharField(default='warning', max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('suppressed', 'Suppressed')], default='pending', max_length=16)),
                ('related_task_id', models.UUIDField(blank=True, null=True)),
                ('related_asset_id', models.UUIDField(blank=True, null=True)),
                ('related_probe_id', models.UUIDField(blank=True, null=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('channels', models.JSONField(blank=True, default=list, help_text='List of channel identifiers used')),
                ('last_error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert Event',
                'verbose_name_plural': 'Alert Events',
                'db_table': 'alerts_event',
            },
        ),
    ]
