# Generated by Django 4.2.13 on 2026-03-18 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128)),
                ('target', models.CharField(help_text='Target to check, e.g. URL, host, or asset identifier', max_length=512)),
                ('protocol', models.CharField(help_text='Protocol such as HTTP/HTTPS/TCP', max_length=32)),
                ('source_type', models.CharField(choices=[('monitoring_request', 'Monitoring Request'), ('probe_schedule', 'Probe Schedule'), ('ad_hoc', 'Ad-hoc')], max_length=32)),
                ('source_id', models.UUIDField(blank=True, help_text='UUID of originating object', null=True)),
                ('executor_type', models.CharField(choices=[('probe', 'Probe'), ('direct', 'Direct')], default='direct', max_length=32)),
                ('executor_config', models.JSONField(blank=True, default=dict, help_text='Backend-specific execution configuration')),
                ('asset_id', models.UUIDField(blank=True, help_text='Optional related asset identifier', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert Check',
                'verbose_name_plural': 'Alert Checks',
                'db_table': 'alerts_check',
            },
        ),
        migrations.CreateModel(
            name='AlertSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cron_expression', models.CharField(blank=True, max_length=64)),
                ('frequency_minutes', models.PositiveIntegerField(default=5)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=16)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('alert_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='alerts.alertcheck')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert Check Schedule',
                'verbose_name_plural': 'Alert Check Schedules',
                'db_table': 'alerts_check_schedule',
            },
        ),
        migrations.CreateModel(
            name='AlertCheckExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('executor_type', models.CharField(choices=[('probe', 'Probe'), ('direct', 'Direct')], default='direct', max_length=32)),
                ('executor_ref', models.CharField(blank=True, help_text='Opaque identifier of the concrete executor (e.g. ProbeNode id)', max_length=128)),
                ('scheduled_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('timeout', 'Timeout'), ('missed', 'Missed')], default='scheduled', max_length=32)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('status_code', models.CharField(blank=True, max_length=32)),
                ('error_message', models.TextField(blank=True)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('source_type', models.CharField(blank=True, max_length=32)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='alerts.alertschedule')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert Check Execution',
                'verbose_name_plural': 'Alert Check Executions',
                'db_table': 'alerts_check_execution',
                'indexes': [models.Index(fields=['schedule', 'scheduled_at'], name='alerts_chec_schedul_06966e_idx'), models.Index(fields=['executor_type', 'executor_ref', 'scheduled_at'], name='alerts_chec_executo_ed7fe7_idx')],
            },
        ),
    ]
