# Generated by Django 4.2.13 on 2026-03-27 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alertcheck_alertschedule_alertcheckexecution'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertcheck',
            name='asset_match_status',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='alertcheck',
            name='asset_record_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alertcheck',
            name='resolved_domain',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='alertcheck',
            name='resolved_system_name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
