// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: probes/v1/gateway.proto

package gateway

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ProbeGateway_Connect_FullMethodName = "/onepro.probes.v1.ProbeGateway/Connect"
)

// ProbeGatewayClient is the client API for ProbeGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProbeGatewayClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (ProbeGateway_ConnectClient, error)
}

type probeGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewProbeGatewayClient(cc grpc.ClientConnInterface) ProbeGatewayClient {
	return &probeGatewayClient{cc}
}

func (c *probeGatewayClient) Connect(ctx context.Context, opts ...grpc.CallOption) (ProbeGateway_ConnectClient, error) {
	stream, err := c.cc.NewStream(ctx, &ProbeGateway_ServiceDesc.Streams[0], ProbeGateway_Connect_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &probeGatewayConnectClient{stream}
	return x, nil
}

type ProbeGateway_ConnectClient interface {
	Send(*ProbeMessage) error
	Recv() (*ServerMessage, error)
	grpc.ClientStream
}

type probeGatewayConnectClient struct {
	grpc.ClientStream
}

func (x *probeGatewayConnectClient) Send(m *ProbeMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *probeGatewayConnectClient) Recv() (*ServerMessage, error) {
	m := new(ServerMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ProbeGatewayServer is the server API for ProbeGateway service.
// All implementations must embed UnimplementedProbeGatewayServer
// for forward compatibility
type ProbeGatewayServer interface {
	Connect(ProbeGateway_ConnectServer) error
	mustEmbedUnimplementedProbeGatewayServer()
}

// UnimplementedProbeGatewayServer must be embedded to have forward compatible implementations.
type UnimplementedProbeGatewayServer struct {
}

func (UnimplementedProbeGatewayServer) Connect(ProbeGateway_ConnectServer) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedProbeGatewayServer) mustEmbedUnimplementedProbeGatewayServer() {}

// UnsafeProbeGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProbeGatewayServer will
// result in compilation errors.
type UnsafeProbeGatewayServer interface {
	mustEmbedUnimplementedProbeGatewayServer()
}

func RegisterProbeGatewayServer(s grpc.ServiceRegistrar, srv ProbeGatewayServer) {
	s.RegisterService(&ProbeGateway_ServiceDesc, srv)
}

func _ProbeGateway_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProbeGatewayServer).Connect(&probeGatewayConnectServer{stream})
}

type ProbeGateway_ConnectServer interface {
	Send(*ServerMessage) error
	Recv() (*ProbeMessage, error)
	grpc.ServerStream
}

type probeGatewayConnectServer struct {
	grpc.ServerStream
}

func (x *probeGatewayConnectServer) Send(m *ServerMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *probeGatewayConnectServer) Recv() (*ProbeMessage, error) {
	m := new(ProbeMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ProbeGateway_ServiceDesc is the grpc.ServiceDesc for ProbeGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProbeGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "onepro.probes.v1.ProbeGateway",
	HandlerType: (*ProbeGatewayServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _ProbeGateway_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "probes/v1/gateway.proto",
}
