# Generated by Django 4.2.26 on 2025-11-12 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('probes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='probenode',
            options={'verbose_name': 'Probe Node', 'verbose_name_plural': 'Probe Nodes'},
        ),
        migrations.AlterModelOptions(
            name='proxymapping',
            options={'verbose_name': 'Proxy Mapping', 'verbose_name_plural': 'Proxy Mappings'},
        ),
        migrations.AlterField(
            model_name='probenode',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='probenode',
            name='supported_protocols',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='probenode',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proxymapping',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proxymapping',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
