# Generated by Django 4.2.26 on 2025-11-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('probes', '0003_probenode_api_token_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='probenode',
            name='agent_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
