# Generated by Django 4.2.26 on 2025-11-20 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('probes', '0008_alter_probeschedule_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProbeScheduleExecution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('missed', 'Missed')], default='scheduled', max_length=32)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('status_code', models.CharField(blank=True, max_length=16)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('probe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_executions', to='probes.probenode')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='probes.probeschedule')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Probe Schedule Execution',
                'verbose_name_plural': 'Probe Schedule Executions',
                'db_table': 'probes_schedule_execution',
                'indexes': [models.Index(fields=['schedule', 'scheduled_at'], name='probes_sche_schedul_001bb8_idx'), models.Index(fields=['probe', 'scheduled_at'], name='probes_sche_probe_i_25815d_idx')],
            },
        ),
    ]
