# Generated by Django 4.2.26 on 2025-11-26 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('probes', '0011_probeconfigrefreshrequest'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='probeconfigrefreshrequest',
            new_name='probes_conf_probe_i_c4df3f_idx',
            old_name='probes_conf_probe_i_5a49c5_idx',
        ),
        migrations.AlterField(
            model_name='probeconfigrefreshrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='probeconfigrefreshrequest',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
